import type { V1State } from './types'

export const v1Transitions: Record<V1State, V1State[]> = {
  DISCOVERED: ['EVALUATED', 'FAILED'],
  EVALUATED: ['APPLY_READY', 'BLOCKED_RETRIEVAL_REQUIRED', 'FAILED'],
  APPLY_READY: ['APPLIED_UNSIGNED', 'BLOCKED_OPERATOR_REVIEW', 'FAILED'],
  APPLIED_UNSIGNED: ['APPLIED_CONFIRMED', 'BLOCKED_OPERATOR_REVIEW', 'FAILED'],
  APPLIED_CONFIRMED: ['EXECUTION_READY', 'FAILED'],
  EXECUTION_READY: ['EXECUTED', 'BLOCKED_RETRIEVAL_REQUIRED', 'FAILED'],
  EXECUTED: ['VALIDATED', 'FAILED'],
  VALIDATED: ['PUBLISHED', 'BLOCKED_ARTIFACT_EMISSION_REQUIRED', 'FAILED'],
  PUBLISHED: ['SUBMISSION_READY', 'FAILED'],
  SUBMISSION_READY: ['SUBMITTED_UNSIGNED', 'BLOCKED_ARTIFACT_EMISSION_REQUIRED', 'FAILED'],
  SUBMITTED_UNSIGNED: ['RECONCILING', 'BLOCKED_OPERATOR_REVIEW', 'FAILED'],
  RECONCILING: ['DONE', 'FAILED'],
  DONE: [],
  FAILED: [],
  BLOCKED_RETRIEVAL_REQUIRED: ['EVALUATED', 'EXECUTION_READY', 'FAILED'],
  BLOCKED_OPERATOR_REVIEW: ['APPLY_READY', 'APPLIED_UNSIGNED', 'SUBMITTED_UNSIGNED', 'FAILED'],
  BLOCKED_ARTIFACT_EMISSION_REQUIRED: ['VALIDATED', 'SUBMISSION_READY', 'FAILED'],
}
